name: example_app
description: Paramify C++ example

parameters:
  - name: audio_gain
    type: double
    value: 1.0
    scope: all
    description: audio gain multiplier

  - name: camera 
    type: group
    description: Camera parameters
    parameters:
      - name: enabled
        type: bool
        value: true
        scope: cli
        description: Enable camera

      - name: device_id
        type: int
        value: 0
      # scope omitted → runtime by default
